name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  test_Q02:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('Q02/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test Q02
        working-directory: ./Q02
        run: mvn clean verify

      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: Q02/target/surefire-reports