name: Deploy Spring Boot to Kubernetes

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar o JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Compilar a aplicação Spring Boot com Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Fazer login no Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Construir a imagem Docker
      - name: Build Docker image
        run: docker build -t mahbuhrer/springboot-app:latest .

      # 6. Fazer push da imagem Docker para o Docker Hub
      - name: Push Docker image
        run: docker push mahbuhrer/springboot-app:latest

      # 7. Configurar o kubectl para acessar o cluster Kubernetes
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      # 8. Atualizar o deployment no Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/springboot-app springboot-app=mahbuhrer/springboot-app:latest
